### ISSUE TITLE
getStickers has stopped working

### ISSUE THREAD

**Issue by eterNEETy** [Kurobyte/Get-Png-Stickers#1]
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	getstickers.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	55463926
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.0.30319.17929
  Problem Signature 06:	4ffa57ca
  Problem Signature 07:	33c7
  Problem Signature 08:	17
  Problem Signature 09:	System.ArgumentNullException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	4a71
  Additional Information 2:	4a710c6173c268dc142f0d9b477dcb30
  Additional Information 3:	7f8f
  Additional Information 4:	7f8f6bafee76f760d264f2623fc19f9b

**Comment by Kurobyte** [comment]
This project is discontinued, if you want you can try [JStickers - https://github.com/Kurobyte/jstickers](https://github.com/Kurobyte/jstickers) it's other(and better) tool I made to download line stickers.
